/**
 * deploy.js — ClaimChain Deployment Script
 *
 * Deployment order:
 *   1. MockUSDC   — mint 1,000,000 USDC to deployer
 *   2. ClaimChain — the core insurance contract
 *   3. Fund ClaimChain with 100,000 USDC liquidity
 *   4. Write deployed addresses to frontend/src/utils/constants.js
 *
 * Usage:
 *   npx hardhat run scripts/deploy.js --network localhost
 *   npx hardhat run scripts/deploy.js --network polygonAmoy
 */

const { ethers, network } = require("hardhat");
const fs   = require("fs");
const path = require("path");

// ── Chainlink addresses per network ──────────────────────────────────────── //
// localhost uses zero-address placeholders so the constructor doesn't revert.
// On Amoy, fill in your real subscription ID in .env.
const CHAINLINK_CONFIG = {
  localhost: {
    // A minimal Functions router mock is not deployed here; the contract
    // still deploys because FunctionsClient only calls the router in
    // sendRequest, which we never hit on localhost (we use mockTriggerPayout).
    router:         "0x0000000000000000000000000000000000000001",
    donId:          ethers.encodeBytes32String("fun-localhost-1"),
    subscriptionId: 1n,
  },
  hardhat: {
    router:         "0x0000000000000000000000000000000000000001",
    donId:          ethers.encodeBytes32String("fun-localhost-1"),
    subscriptionId: 1n,
  },
  polygonAmoy: {
    // Chainlink Functions router on Polygon Amoy (v1)
    router:         "0xC22a79eBA640940ABB6dF0f7982cc119578E11De",
    donId:          ethers.encodeBytes32String(
                      process.env.CHAINLINK_DON_ID || "fun-polygon-amoy-1"
                    ),
    subscriptionId: BigInt(process.env.CHAINLINK_SUBSCRIPTION_ID || "0"),
  },
};

// ── Load Chainlink Functions JS source ──────────────────────────────────── //
function loadFlightSource() {
  const srcPath = path.resolve(__dirname, "../chainlink/flightStatusSource.js");
  if (!fs.existsSync(srcPath)) {
    throw new Error(`flightStatusSource.js not found at: ${srcPath}`);
  }
  return fs.readFileSync(srcPath, "utf8");
}

// ── Write frontend/.env with deployed addresses ──────────────────────────── //
function writeEnv(usdcAddress, claimChainAddress, chainId) {
  const envPath = path.resolve(__dirname, "../frontend/.env");

  const content = [
    `# Auto-generated by scripts/deploy.js on ${new Date().toISOString()}`,
    `# Do NOT commit this file — it is listed in .gitignore`,
    `VITE_CONTRACT_ADDRESS=${claimChainAddress}`,
    `VITE_USDC_ADDRESS=${usdcAddress}`,
    `VITE_CHAIN_ID=${chainId}`,
    `VITE_WALLETCONNECT_PROJECT_ID=claimchain_demo`,
    "",
  ].join("\n");

  fs.writeFileSync(envPath, content, "utf8");
  console.log("  ✔ frontend/.env updated with deployed addresses");
}

// ── Main ─────────────────────────────────────────────────────────────────── //
async function main() {
  const networkName = network.name;
  console.log(`\n🚀 Deploying ClaimChain on "${networkName}"...\n`);

  const [deployer] = await ethers.getSigners();
  console.log(`  Deployer : ${deployer.address}`);
  console.log(
    `  Balance  : ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH\n`
  );

  const cfg = CHAINLINK_CONFIG[networkName];
  if (!cfg) {
    throw new Error(`No Chainlink config for network "${networkName}". Add it to CHAINLINK_CONFIG.`);
  }

  // ── 1. Deploy MockUSDC ──────────────────────────────────────────────── //
  console.log("1️⃣  Deploying MockUSDC...");
  const MockUSDC = await ethers.getContractFactory("MockUSDC");
  const mockUSDC = await MockUSDC.deploy(deployer.address);
  await mockUSDC.waitForDeployment();
  const usdcAddress = await mockUSDC.getAddress();
  console.log(`   MockUSDC deployed at : ${usdcAddress}`);

  // Mint 1,000,000 USDC to deployer.
  const mintAmount = ethers.parseUnits("1000000", 6);
  await (await mockUSDC.mint(deployer.address, mintAmount)).wait();
  console.log(`   Minted 1,000,000 USDC to deployer`);

  // ── 2. Deploy ClaimChain ─────────────────────────────────────────────── //
  console.log("\n2️⃣  Deploying ClaimChain...");
  const flightSource = loadFlightSource();

  const ClaimChain = await ethers.getContractFactory("ClaimChain");
  const claimChain = await ClaimChain.deploy(
    cfg.router,
    cfg.donId,
    cfg.subscriptionId,
    usdcAddress,
    deployer.address,   // insurerTreasury = deployer for demo
    flightSource
  );
  await claimChain.waitForDeployment();
  const contractAddress = await claimChain.getAddress();
  console.log(`   ClaimChain deployed at : ${contractAddress}`);

  // ── 3. Fund ClaimChain with liquidity ───────────────────────────────── //
  console.log("\n3️⃣  Funding ClaimChain with 100,000 USDC liquidity...");
  const liquidityAmount = ethers.parseUnits("100000", 6);
  await (
    await mockUSDC.approve(contractAddress, liquidityAmount)
  ).wait();
  await (
    await mockUSDC.transfer(contractAddress, liquidityAmount)
  ).wait();
  console.log(`   ClaimChain USDC balance : ${ethers.formatUnits(
    await mockUSDC.balanceOf(contractAddress), 6
  )} USDC`);

  // ── 4. Write frontend/.env ──────────────────────────────────────────── //
  console.log("\n4️⃣  Writing frontend environment file...");
  const chainId = (await ethers.provider.getNetwork()).chainId;
  writeEnv(usdcAddress, contractAddress, chainId.toString());

  // ── Summary ─────────────────────────────────────────────────────────── //
  console.log("\n✅  Deployment complete!\n");
  console.log("┌─────────────────────────────────────────────────────────────┐");
  console.log(`│ Network        : ${networkName.padEnd(43)}│`);
  console.log(`│ MockUSDC       : ${usdcAddress.padEnd(43)}│`);
  console.log(`│ ClaimChain     : ${contractAddress.padEnd(43)}│`);
  console.log("└─────────────────────────────────────────────────────────────┘");
  console.log("\nNext steps:");
  console.log("  • Import a Hardhat account into MetaMask (see README)");
  console.log("  • cd frontend && npm run dev");
  console.log("  • Use MockTriggerToggle in the UI to simulate a payout\n");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
